# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp_control_plane.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'mcp_control_plane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17mcp_control_plane.proto\x12\x07\x61os.mcp\"$\n\x10ListToolsRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"1\n\x11ListToolsResponse\x12\x1c\n\x05tools\x18\x01 \x03(\x0b\x32\r.aos.mcp.Tool\"?\n\x04Tool\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cinput_schema\x18\x03 \x01(\t\"a\n\x0f\x43\x61llToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x11\n\targuments\x18\x02 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\x12\x10\n\x08trace_id\x18\x04 \x01(\t\"K\n\x10\x43\x61llToolResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x10\n\x08is_error\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2\x91\x01\n\nMCPService\x12\x42\n\tListTools\x12\x19.aos.mcp.ListToolsRequest\x1a\x1a.aos.mcp.ListToolsResponse\x12?\n\x08\x43\x61llTool\x12\x18.aos.mcp.CallToolRequest\x1a\x19.aos.mcp.CallToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_control_plane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTTOOLSREQUEST']._serialized_start=36
  _globals['_LISTTOOLSREQUEST']._serialized_end=72
  _globals['_LISTTOOLSRESPONSE']._serialized_start=74
  _globals['_LISTTOOLSRESPONSE']._serialized_end=123
  _globals['_TOOL']._serialized_start=125
  _globals['_TOOL']._serialized_end=188
  _globals['_CALLTOOLREQUEST']._serialized_start=190
  _globals['_CALLTOOLREQUEST']._serialized_end=287
  _globals['_CALLTOOLRESPONSE']._serialized_start=289
  _globals['_CALLTOOLRESPONSE']._serialized_end=364
  _globals['_MCPSERVICE']._serialized_start=367
  _globals['_MCPSERVICE']._serialized_end=512
# @@protoc_insertion_point(module_scope)
