# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mcp_control_plane_pb2 as mcp__control__plane__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp_control_plane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MCPServiceStub:
    """MCP 控制面：任务指令、工具发现、状态同步
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTools = channel.unary_unary(
                '/aos.mcp.MCPService/ListTools',
                request_serializer=mcp__control__plane__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=mcp__control__plane__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/aos.mcp.MCPService/CallTool',
                request_serializer=mcp__control__plane__pb2.CallToolRequest.SerializeToString,
                response_deserializer=mcp__control__plane__pb2.CallToolResponse.FromString,
                _registered_method=True)


class MCPServiceServicer:
    """MCP 控制面：任务指令、工具发现、状态同步
    """

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MCPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=mcp__control__plane__pb2.ListToolsRequest.FromString,
                    response_serializer=mcp__control__plane__pb2.ListToolsResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=mcp__control__plane__pb2.CallToolRequest.FromString,
                    response_serializer=mcp__control__plane__pb2.CallToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aos.mcp.MCPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aos.mcp.MCPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MCPService:
    """MCP 控制面：任务指令、工具发现、状态同步
    """

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aos.mcp.MCPService/ListTools',
            mcp__control__plane__pb2.ListToolsRequest.SerializeToString,
            mcp__control__plane__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aos.mcp.MCPService/CallTool',
            mcp__control__plane__pb2.CallToolRequest.SerializeToString,
            mcp__control__plane__pb2.CallToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
