# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import meta_orchestrator_pb2 as meta__orchestrator__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in meta_orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetaOrchestratorStub:
    """L3.5 元调度路由层：三项核心职责
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteIntent = channel.unary_unary(
                '/aos.meta.MetaOrchestrator/RouteIntent',
                request_serializer=meta__orchestrator__pb2.RouteIntentRequest.SerializeToString,
                response_deserializer=meta__orchestrator__pb2.RouteIntentResponse.FromString,
                _registered_method=True)
        self.QueryPriority = channel.unary_unary(
                '/aos.meta.MetaOrchestrator/QueryPriority',
                request_serializer=meta__orchestrator__pb2.QueryPriorityRequest.SerializeToString,
                response_deserializer=meta__orchestrator__pb2.QueryPriorityResponse.FromString,
                _registered_method=True)
        self.InjectPersona = channel.unary_unary(
                '/aos.meta.MetaOrchestrator/InjectPersona',
                request_serializer=meta__orchestrator__pb2.InjectPersonaRequest.SerializeToString,
                response_deserializer=meta__orchestrator__pb2.InjectPersonaResponse.FromString,
                _registered_method=True)


class MetaOrchestratorServicer:
    """L3.5 元调度路由层：三项核心职责
    """

    def RouteIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPriority(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectPersona(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetaOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteIntent,
                    request_deserializer=meta__orchestrator__pb2.RouteIntentRequest.FromString,
                    response_serializer=meta__orchestrator__pb2.RouteIntentResponse.SerializeToString,
            ),
            'QueryPriority': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPriority,
                    request_deserializer=meta__orchestrator__pb2.QueryPriorityRequest.FromString,
                    response_serializer=meta__orchestrator__pb2.QueryPriorityResponse.SerializeToString,
            ),
            'InjectPersona': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectPersona,
                    request_deserializer=meta__orchestrator__pb2.InjectPersonaRequest.FromString,
                    response_serializer=meta__orchestrator__pb2.InjectPersonaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aos.meta.MetaOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aos.meta.MetaOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetaOrchestrator:
    """L3.5 元调度路由层：三项核心职责
    """

    @staticmethod
    def RouteIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aos.meta.MetaOrchestrator/RouteIntent',
            meta__orchestrator__pb2.RouteIntentRequest.SerializeToString,
            meta__orchestrator__pb2.RouteIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPriority(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aos.meta.MetaOrchestrator/QueryPriority',
            meta__orchestrator__pb2.QueryPriorityRequest.SerializeToString,
            meta__orchestrator__pb2.QueryPriorityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectPersona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aos.meta.MetaOrchestrator/InjectPersona',
            meta__orchestrator__pb2.InjectPersonaRequest.SerializeToString,
            meta__orchestrator__pb2.InjectPersonaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
