# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meta_orchestrator.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'meta_orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17meta_orchestrator.proto\x12\x08\x61os.meta\"[\n\x12RouteIntentRequest\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\x12\x10\n\x08trace_id\x18\x04 \x01(\t\"T\n\x13RouteIntentResponse\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x16\n\x0epersona_config\x18\x03 \x01(\t\"\'\n\x14QueryPriorityRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"/\n\x15QueryPriorityResponse\x12\x16\n\x0epriority_level\x18\x01 \x01(\x05\";\n\x14InjectPersonaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\"/\n\x15InjectPersonaResponse\x12\x16\n\x0epersona_config\x18\x01 \x01(\t2\x82\x02\n\x10MetaOrchestrator\x12J\n\x0bRouteIntent\x12\x1c.aos.meta.RouteIntentRequest\x1a\x1d.aos.meta.RouteIntentResponse\x12P\n\rQueryPriority\x12\x1e.aos.meta.QueryPriorityRequest\x1a\x1f.aos.meta.QueryPriorityResponse\x12P\n\rInjectPersona\x12\x1e.aos.meta.InjectPersonaRequest\x1a\x1f.aos.meta.InjectPersonaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta_orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEINTENTREQUEST']._serialized_start=37
  _globals['_ROUTEINTENTREQUEST']._serialized_end=128
  _globals['_ROUTEINTENTRESPONSE']._serialized_start=130
  _globals['_ROUTEINTENTRESPONSE']._serialized_end=214
  _globals['_QUERYPRIORITYREQUEST']._serialized_start=216
  _globals['_QUERYPRIORITYREQUEST']._serialized_end=255
  _globals['_QUERYPRIORITYRESPONSE']._serialized_start=257
  _globals['_QUERYPRIORITYRESPONSE']._serialized_end=304
  _globals['_INJECTPERSONAREQUEST']._serialized_start=306
  _globals['_INJECTPERSONAREQUEST']._serialized_end=365
  _globals['_INJECTPERSONARESPONSE']._serialized_start=367
  _globals['_INJECTPERSONARESPONSE']._serialized_end=414
  _globals['_METAORCHESTRATOR']._serialized_start=417
  _globals['_METAORCHESTRATOR']._serialized_end=675
# @@protoc_insertion_point(module_scope)
